/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminAuthenticatedImport } from './routes/admin/_authenticated'
import { Route as AdminAuthenticatedDashboardOrdersApprovedOrdersImport } from './routes/admin/_authenticated/dashboard/orders/approved-orders'

// Create Virtual Routes

const AdminImport = createFileRoute('/admin')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const AdminIndexLazyImport = createFileRoute('/admin/')()
const AdminLoginLazyImport = createFileRoute('/admin/login')()
const AdminAuthenticatedDashboardIndexLazyImport = createFileRoute(
  '/admin/_authenticated/dashboard/',
)()
const AdminAuthenticatedDashboardCustomersLazyImport = createFileRoute(
  '/admin/_authenticated/dashboard/customers',
)()
const AdminAuthenticatedDashboardProductsIndexLazyImport = createFileRoute(
  '/admin/_authenticated/dashboard/products/',
)()
const AdminAuthenticatedDashboardOrdersIndexLazyImport = createFileRoute(
  '/admin/_authenticated/dashboard/orders/',
)()
const AdminAuthenticatedDashboardProductsCreateLazyImport = createFileRoute(
  '/admin/_authenticated/dashboard/products/create',
)()

// Create/Update Routes

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))

const AdminLoginLazyRoute = AdminLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin/login.lazy').then((d) => d.Route))

const AdminAuthenticatedRoute = AdminAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAuthenticatedDashboardIndexLazyRoute =
  AdminAuthenticatedDashboardIndexLazyImport.update({
    path: '/dashboard/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/admin/_authenticated/dashboard/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminAuthenticatedDashboardCustomersLazyRoute =
  AdminAuthenticatedDashboardCustomersLazyImport.update({
    path: '/dashboard/customers',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/admin/_authenticated/dashboard/customers.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminAuthenticatedDashboardProductsIndexLazyRoute =
  AdminAuthenticatedDashboardProductsIndexLazyImport.update({
    path: '/dashboard/products/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/admin/_authenticated/dashboard/products/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminAuthenticatedDashboardOrdersIndexLazyRoute =
  AdminAuthenticatedDashboardOrdersIndexLazyImport.update({
    path: '/dashboard/orders/',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/admin/_authenticated/dashboard/orders/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminAuthenticatedDashboardProductsCreateLazyRoute =
  AdminAuthenticatedDashboardProductsCreateLazyImport.update({
    path: '/dashboard/products/create',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/admin/_authenticated/dashboard/products/create.lazy').then(
      (d) => d.Route,
    ),
  )

const AdminAuthenticatedDashboardOrdersApprovedOrdersRoute =
  AdminAuthenticatedDashboardOrdersApprovedOrdersImport.update({
    path: '/dashboard/orders/approved-orders',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginLazyImport
      parentRoute: typeof AdminImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof AdminImport
    }
    '/admin/_authenticated/dashboard/customers': {
      id: '/admin/_authenticated/dashboard/customers'
      path: '/dashboard/customers'
      fullPath: '/admin/dashboard/customers'
      preLoaderRoute: typeof AdminAuthenticatedDashboardCustomersLazyImport
      parentRoute: typeof AdminAuthenticatedImport
    }
    '/admin/_authenticated/dashboard/': {
      id: '/admin/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthenticatedDashboardIndexLazyImport
      parentRoute: typeof AdminAuthenticatedImport
    }
    '/admin/_authenticated/dashboard/orders/approved-orders': {
      id: '/admin/_authenticated/dashboard/orders/approved-orders'
      path: '/dashboard/orders/approved-orders'
      fullPath: '/admin/dashboard/orders/approved-orders'
      preLoaderRoute: typeof AdminAuthenticatedDashboardOrdersApprovedOrdersImport
      parentRoute: typeof AdminAuthenticatedImport
    }
    '/admin/_authenticated/dashboard/products/create': {
      id: '/admin/_authenticated/dashboard/products/create'
      path: '/dashboard/products/create'
      fullPath: '/admin/dashboard/products/create'
      preLoaderRoute: typeof AdminAuthenticatedDashboardProductsCreateLazyImport
      parentRoute: typeof AdminAuthenticatedImport
    }
    '/admin/_authenticated/dashboard/orders/': {
      id: '/admin/_authenticated/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/admin/dashboard/orders'
      preLoaderRoute: typeof AdminAuthenticatedDashboardOrdersIndexLazyImport
      parentRoute: typeof AdminAuthenticatedImport
    }
    '/admin/_authenticated/dashboard/products/': {
      id: '/admin/_authenticated/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/admin/dashboard/products'
      preLoaderRoute: typeof AdminAuthenticatedDashboardProductsIndexLazyImport
      parentRoute: typeof AdminAuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  AdminRoute: AdminRoute.addChildren({
    AdminAuthenticatedRoute: AdminAuthenticatedRoute.addChildren({
      AdminAuthenticatedDashboardCustomersLazyRoute,
      AdminAuthenticatedDashboardIndexLazyRoute,
      AdminAuthenticatedDashboardOrdersApprovedOrdersRoute,
      AdminAuthenticatedDashboardProductsCreateLazyRoute,
      AdminAuthenticatedDashboardOrdersIndexLazyRoute,
      AdminAuthenticatedDashboardProductsIndexLazyRoute,
    }),
    AdminLoginLazyRoute,
    AdminIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/admin"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/admin": {
      "filePath": "admin",
      "children": [
        "/admin/_authenticated",
        "/admin/login",
        "/admin/"
      ]
    },
    "/admin/_authenticated": {
      "filePath": "admin/_authenticated.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_authenticated/dashboard/customers",
        "/admin/_authenticated/dashboard/",
        "/admin/_authenticated/dashboard/orders/approved-orders",
        "/admin/_authenticated/dashboard/products/create",
        "/admin/_authenticated/dashboard/orders/",
        "/admin/_authenticated/dashboard/products/"
      ]
    },
    "/admin/login": {
      "filePath": "admin/login.lazy.tsx",
      "parent": "/admin"
    },
    "/admin/": {
      "filePath": "admin/index.lazy.tsx",
      "parent": "/admin"
    },
    "/admin/_authenticated/dashboard/customers": {
      "filePath": "admin/_authenticated/dashboard/customers.lazy.tsx",
      "parent": "/admin/_authenticated"
    },
    "/admin/_authenticated/dashboard/": {
      "filePath": "admin/_authenticated/dashboard/index.lazy.tsx",
      "parent": "/admin/_authenticated"
    },
    "/admin/_authenticated/dashboard/orders/approved-orders": {
      "filePath": "admin/_authenticated/dashboard/orders/approved-orders.tsx",
      "parent": "/admin/_authenticated"
    },
    "/admin/_authenticated/dashboard/products/create": {
      "filePath": "admin/_authenticated/dashboard/products/create.lazy.tsx",
      "parent": "/admin/_authenticated"
    },
    "/admin/_authenticated/dashboard/orders/": {
      "filePath": "admin/_authenticated/dashboard/orders/index.lazy.tsx",
      "parent": "/admin/_authenticated"
    },
    "/admin/_authenticated/dashboard/products/": {
      "filePath": "admin/_authenticated/dashboard/products/index.lazy.tsx",
      "parent": "/admin/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
